{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute'
         html_class='full'
         twitter_accounts=ezini( 'xrowTwittAccounts', 'AvailableTwitterAccounts', 'xrowtwitt.ini' )
         facebook_accounts=ezini( 'xrowTwittAccounts', 'AvailableFacebookAccounts', 'xrowtwitt.ini' )}
{if $attribute.data_int|ne(1)}
    <textarea id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_xrowtwitt_text_{$attribute.id}" cols="70" rows="10">{$attribute.content|wash}</textarea>
{else}
    <div class="box">
        {$attribute.content|wash}
    </div>
{/if}
{if $attribute.data_int|ne(1)}
<div class="block">
    <div class="element">
        <label>{'Twitter Account'|i18n( 'datatypes/xrowtwitt' )}</label>
        <select id="ezcoa-{$attribute.id}_twitter" class="xrowtwitt twitterselect" name="{$attribute_base}_xrowtwitt_twitter_{$attribute.id}">
            <option value="-1">{'no selection'|i18n( 'datatypes/xrowtwitt' )}</option>
            {foreach $twitter_accounts as $twitter_acc}
                <option value="{$twitter_acc}">{$twitter_acc}</option>
            {/foreach}
        </select>
    </div>
    <div class="element">
        <label>{'Facebook Account'|i18n( 'datatypes/xrowtwitt' )}</label>
        <select id="ezcoa-{$attribute.id}_facebook" class="xrowtwitt facebookselect" name="{$attribute_base}_xrowtwitt_facebook_{$attribute.id}">
            <option value="-1">{'no selection'|i18n( 'datatypes/xrowtwitt' )}</option>
            {foreach $facebook_accounts as $fb_acc}
                <option value="{$fb_acc}">{$fb_acc}</option>
            {/foreach}
        </select>
    </div>
</div>
{/if}
{/default}
